name: scp-diff
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.23.1
  - pillow=10.2.0
  - pip=20.3.3
  - python=3.8.5
  - pip:
      - aiohttp==3.9.3
      - einops==0.7.0
      - ipython==8.12.3
      - lightning-utilities==0.10.1
      - matplotlib-inline==0.1.6
      - multiprocess==0.70.16
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - opencv-python==4.9.0.80
      - p-tqdm==1.4.0
      - prompt-toolkit==3.0.43
      - pytorch-lightning==1.6.5
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests-oauthlib==1.4.0
      - rsa==4.9
      - safetensors==0.4.2
      - sentencepiece==0.2.0
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - timm==0.9.16
      - tokenizers==0.15.2
      - torchmetrics==1.3.1
      - tqdm==4.66.2
      - transformers==4.38.2
      - yarl==1.9.4
      - zipp==3.17.0
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.2.0
      - torchvision==0.17.0